// Generated by CoffeeScript 1.7.1
(function() {
  var castAway;

  castAway = window.castAway = new CastAway({
    applicationID: "517348B1",
    namespace: "urn:x-cast:json"
  });

  castAway.on("receivers:available", function() {
    console.log("receivers available");
    return castAway.requestSession(function(err, session) {
      if (err) {
        return console.log("Error getting session", err);
      }
      return $("#send-message").click(function(e) {
        var val;
        val = $("#urls").val();
        console.log("Sending " + val);
        $("#urls").val("");
        return session.send("update", {
          urls: val.split("\n")
        }, function(err, data) {
          if (err) {
            return console.log("error", err);
          }
        });
      });
    });
  });

  castAway.initialize(function(err, data) {
    if (err) {
      return console.log("error initialized", err);
    } else {
      return console.log("initialized", data);
    }
  });

}).call(this);
